### ISSUE TITLE
signature token vulnerable

### ISSUE THREAD

**Issue by danielhv10** [omniT/zero#13]

**Comment by Butakus** [comment]
I did some research through the jwt-simple [source code](https://github.com/hokaccha/node-jwt-simple) and the [jwt specification](http://tools.ietf.org/html/draft-ietf-oauth-json-web-token-25).
The jws-simple encode function does NOT encrypt the (header+payload), but just sign it and appends the signature to it. The header, the payload and the sign are encoded into a base64url form and concatenated with dots '.'. The functions used to encode in base64url are:

``` javascript
function base64urlEncode(str) {
    return base64urlEscape(new Buffer(str).toString('base64'));
}
function base64urlEscape(str) {
    return str.replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
}
```

So, with jwt the token is just signed (and not encrypted) because the server only needs to verify that the token received has a valid signature.
It is true that if someone stole the token, he could gain access to the payload, and he could use the token to access to the application (he would have the credentials). This is why the token must always travel under HTTPS.
Anyway, this is not a bug in jwt (neither a bug in jwt-simple), but it's just the way it works.

We could also encrypt the token's payload before signing, but it would be a waste of computing resources, and we don't really need it for the session (there is no sensitive data in the payload and it's not easy to stole a token).

BTW, in the [jwt debugger](http://jwt.io/#debugger) you can see how it decodes the data, but if you don't insert the right key, it will say below that the signature is not valid.

More info:
https://stormpath.com/blog/token-auth-spa/
https://stormpath.com/blog/jwt-the-right-way/
